server:
  port: 8181
  servlet:
    session:
      timeout: 30d
      cookie:
        max-age: 30d

spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/pms
    driver-class-name: org.postgresql.Driver
    username: pms
    password: pms
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: api
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.mason.common.event
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ${DISCORD_CLIENT_ID}
            client-secret: ${DISCORD_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/discord"
            scope: identify, email, guilds.members.read
            client-name: Discord
        provider:
          discord:
            authorization-uri: https://discord.com/api/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: id

app:
  base-url: ${APP_BASE_URL:http://localhost:8181}
  discord:
    guild-id: ${DISCORD_GUILD_ID}
